# -*- coding: utf-8 -*-
"""Plotly_Ass_A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3AwxWIU0yPCsjBb2SY1E3kb1srPL6ZR
"""

import seaborn as sns
import plotly.express as px

"""# Qus 1"""

! pip install plotly

titanic=sns.load_dataset("titanic")
fig=px.scatter(titanic,x="age",y="fare",title="Scatter Plot")
fig.show()

"""# Qus 2"""

tips=px.data.tips()
fig=px.box(tips,x="day",y="total_bill",title="Box Plot")
fig.show()

"""# Qus 3"""

fig=px.histogram(tips,x="sex",y="total_bill",histfunc="sum",color="day",pattern_shape="smoker",title="Histogram")
fig.show()



"""# Qus 4"""

iris=sns.load_dataset("iris")

iris

fig=px.scatter_matrix(iris,dimensions=["sepal_length","sepal_width","petal_length","petal_width"],color="species",title="Scatter Matrix")
fig.show()

"""# Qus 5

The distplot (distribution plot ) is a type of plot used to visualize the ditribution of single variable dataset. It combines a histogram with kernel density estimate (KDE) plot , allowing you to see the shape of the distribution , the presence of peaks or gaps ,and the overall spread of the data.
"""

import numpy as np
np.random.seed(0)
data=np.random.normal(0,1,1000)

fig=px.histogram(x=data,nbins=30,title="Distribution Plot")
fig.show()

